global: 
  applicationName: accessibility
  region: us-central1
node-web-service:
  # disableHealthChecking: true
  database:
    enabled: true
  cache:
    enabled: false
  cloud-sql:
    enabled: false
    databaseVersion: POSTGRES_11
  image:
    name: gcr.io/g5-images/accessibility
  isInternetFacing: true
  hasMetrics: false
  replicaCount: 2
  revisionHistoryLimit: 1
  resources:
    limits:
      cpu: 1000m
      memory: 2000Mi
    requests:
      cpu: 200m
      memory: 300Mi
  configurations:
    staging:
      configMapData:
        BROWSER_URL: 'https://accessibility-opex-staging.g5devops.com'
        BASE_URL: 'accessibility-opex-staging.g5devops.com'
    prime:
      configMapData:
        BROWSER_URL: 'https://accessibility-opex-prime.g5devops.com'
        BASE_URL: 'accessibility-opex-prime.g5devops.com'
    production:
      configMapData:
        BROWSER_URL: 'https://accessibility.g5marketingcloud.com/'
        BASE_URL: 'accessibility.g5marketingcloud.com'
  env:
    - name: BROWSER_URL
      valueFrom:
        configMapKeyRef:
          name: accessibility
          key: BROWSER_URL
    - name: DATABASE_HOST
      valueFrom:
        configMapKeyRef:
          name: crs-a-sqlinstance
          key: private-ip-address
    - name: DATABASE_DIALECT
      value: postgres
    - name: DATABASE_IDLE
      value: "10000"
    - name: DATABASE_AQUIRE
      value: "10000"
    - name: DATABASE_EVICT
      value: "10000"
    - name: DATABASE_MIN_CONNECTIONS
      value: "0"
    - name: DATABASE_MAX_CONNECTIONS
      value: "100"
    - name: DATABASE_PORT
      value: "5432"
    - name: DATABASE_SSL
      value: "false"
    - name: DATABASE_LOGGING
      value: "false"
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: crs-a-sqluser-password 
          key: password 
    - name: DATABASE_URL
      value: $(DATABASE_DIALECT)://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)
