apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{  .Release.Name }}"
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
  annotations: 
    reloader.stakater.com/search: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: "{{  .Release.Name }}"
      version: "current"
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        app: "{{  .Release.Name }}"
        version: "current"
    spec:
      containers:
      - name: "{{  .Chart.Name  }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.servicePort}}
        resources:
          requests:
            cpu: "{{ .Values.image.resources.requests.cpu }}"
            memory: "{{ .Values.image.resources.requests.memory }}"
        env:
          - name: TOKEN_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: TOKEN_HOST
          - name: G5_AUTH_ENDPOINT
            value: "https://auth.g5search.com/oauth/authorize"
          - name: G5_TOKEN_ENDPOINT
            value: "https://auth.g5search.com/oauth/token"
          - name: G5_AUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: wcag
                key: G5_AUTH_CLIENT_ID
          - name: G5_AUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: wcag
                key: G5_AUTH_CLIENT_SECRET 
          - name: G5_AUTH_REDIRECT_URI
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: G5_AUTH_REDIRECT_URI
          - name: BROWSER_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: BROWSER_URL
          - name: G5_AUTH_ME_ENDPOINT
            value: "https://auth.g5search.com/v1/me"
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: wcag
                key: SESSION_SECRET
          - name: SLACK_FEEDBACK_URL
            valueFrom:
              secretKeyRef:
                name: wcag
                key: SLACK_FEEDBACK_URL
          - name: GKE
            value: "true"
          - name: BROWSER_URL
            value: "accessibility.g5marketingcloud.com"
          - name: DATABASE_MAX_CONNECTIONS
            value: "10"
          - name: DATABASE_MIN_CONNECTIONS
            value: "0"
          - name: DATABASE_DIALECT
            value: postgres
          - name: DATABASE_IDLE
            value: "10000"
          - name: DATABASE_AQUIRE
            value: "10000"
          - name: DATABASE_EVICT
            value: "10000"
          - name: DATABASE_PORT
            value: "5432"
          - name: DATABASE_SSL
            value: "false"
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ include "cloudsql.hostConfigMapName" (list (include "cloud-helper.values.applicationName" $) (get .Values .Values.activeCloudSQLSubchart)) }}
                key: {{ include "cloudsql.hostConfigMapKey" . }}
          - name: DATABASE_NAME
            value: {{ include "cloudsql.databaseName" (list (include "cloud-helper.values.applicationName" $) (get .Values .Values.activeCloudSQLSubchart)) }}
          - name: DATABASE_USER
            value: {{ include "cloudsql.userName" (list (include "cloud-helper.values.applicationName" $) (get .Values .Values.activeCloudSQLSubchart)) }}
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "cloudsql.passwordSecretName" (list (include "cloud-helper.values.applicationName" $) (get .Values .Values.activeCloudSQLSubchart)) }}
                key: {{ include "cloudsql.passwordSecretKey" . }}
          - name: DATABASE_URL
            value: $(DATABASE_DIALECT)://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)
          - name: PORT
            value : "{{ .Values.service.servicePort }}"
        {{- if .Values.image.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.image.livenessProbe | indent 10 }}
        {{- end }}
        {{- if .Values.image.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.image.readinessProbe | indent 10 }}
        {{- end }}